# Minimal Rasa Configuration for Memory-Constrained Deployment
version: "3.1"
language: en
assistant_id: marcy_assistant

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    max_features: 100  # Reduced from 1000
  - name: DIETClassifier
    epochs: 5  # Reduced from 100
    batch_size: 16  # Reduced from 64
    number_of_transformer_layers: 1  # Reduced from 2
    transformer_size: 32  # Reduced from 256
    use_masked_language_model: false  # Disabled for memory
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 5  # Reduced from 100
    batch_size: 16  # Reduced from 64
    number_of_transformer_layers: 1  # Reduced from 2
    transformer_size: 32  # Reduced from 256
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: MemoizationPolicy
    max_history: 2  # Reduced from 5
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 2  # Reduced from 5
    epochs: 5  # Reduced from 100
    batch_size: 16  # Reduced from 32
  - name: TEDPolicy
    max_history: 2  # Reduced from 5
    epochs: 5  # Reduced from 100
    batch_size: 16  # Reduced from 32
    number_of_transformer_layers: 1  # Reduced from 2
    transformer_size: 32  # Reduced from 256
    use_masked_language_model: false  # Disabled for memory