recipe: default.v1
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 10
    embedding_dimension: 20
    constrain_similarities: true
    batch_size: [16, 32]
    learning_rate: 0.001
  - name: EntitySynonymMapper

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    enable_fallback_prediction: true
  - name: MemoizationPolicy